#
# Makefile
#

CIRCLEHOME = ../..
OUTPUT_DIR	= build/

# OBJS	= main.o kernel.o
SRCS = main.cpp kernel.cpp

LIBS	= $(CIRCLEHOME)/lib/input/libinput.a \
	  $(CIRCLEHOME)/lib/libcircle.a

include ../Rules.mk
